version: '3.9'

services:

  mongo:
    image: mongo
    restart: always

  redis:
    image: redis
    restart: always

  bot-status:
    image: gewoonjaap/discord-bot-status-displayer:latest
    restart: always
    env_file:
      - .env
    environment:
      - ACTIVITY_TYPE=PLAYING
      - ACTIVITY_NAME=Watering the christmas trees

  grow-a-tree:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    restart: always
    volumes:
      - .:/usr/app
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1"
      interval: 1m
      timeout: 30s
      retries: 2
      start_period: 30s

  # The Unleash server contains the Unleash configuration and
  # communicates with server-side SDKs and the Unleash Proxy
  unleash-web:
    image: unleashorg/unleash-server:latest
    ports:
      - "5489:4242"
    environment:
      # This points Unleash to its backing database (defined in the `db` section below)
      DATABASE_URL: "postgres://postgres:unleash@db/db"
      # Disable SSL for database connections.
      DATABASE_SSL: "false"
      # Changing log levels:
      LOG_LEVEL: "warn"
    depends_on:
      db:
        condition: service_healthy
    command: [ "node", "index.js" ]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  db:
    image: postgres:15
    environment:
      # create a database called `db`
      POSTGRES_DB: "db"
      # trust incoming connections blindly (DON'T DO THIS IN PRODUCTION!)
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - christmas_tree_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=postgres",
          "--host=127.0.0.1",
          "--port=5432"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

volumes:
  christmas_tree_postgres_data: