version: '3'

services:

  image-server:
    image: gat-image-server:latest
    volumes:
      - /var/www/tiling-images/trees:/var/www/images
    restart: unless-stopped

  mongo:
    image: mongo
    volumes:
      - /opt/databases/grow-a-tree:/data/db
    ports: 
      - "27017:27017"

  redis:
    image: redis

  grow-a-tree:
    container_name: grow-a-tree
    image: grow-a-tree:latest
    ports:
      - "8089:8080"
    restart: unless-stopped

