version: '3.9'

services:

  mongo:
    image: mongo
    restart: always

  redis:
    image: redis
    restart: always

  bot-status:
    image: gewoonjaap/discord-bot-status-displayer:latest
    restart: always
    env_file:
      - .env.prod
    environment:
      - ACTIVITY_TYPE=PLAYING
      - ACTIVITY_NAME=Watering the christmas trees

  grow-a-tree:
    image: ghcr.io/gewoonjaap/grow-a-tree:latest
    ports:
      - "8089:8080"
    restart: always
    env_file:
      - .env.prod

  unleash-web:
    image: unleashorg/unleash-server:latest
    ports:
      - "5489:4242"
    environment:
      DATABASE_URL: "postgres://postgres:unleash@db/db"
      DATABASE_SSL: "false"
      LOG_LEVEL: "warn"
    depends_on:
      db:
        condition: service_healthy
    command: [ "node", "index.js" ]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - christmas_tree_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=postgres",
          "--host=127.0.0.1",
          "--port=5432"
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

volumes:
  christmas_tree_postgres_data:
