version: '3'

services:

  mongo:
    image: mongo
    restart: always

  redis:
    image: redis
    restart: always

  bot-status:
    image: gewoonjaap/discord-bot-status-displayer:latest
    restart: always
    env_file:
      - .env
    environment:
      - ACTIVITY_TYPE=PLAYING
      - ACTIVITY_NAME=Watering the christmas trees

  grow-a-tree:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    restart: always
    volumes:
      - .:/usr/app
