version: '3'

services:

  mongo:
    image: mongo

  redis:
    image: redis

  grow-a-tree:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    restart: unless-stopped
    volumes:
      - .:/usr/app
